from unittest.mock import patch

from app.services.forensics_audio import AudioForensicsResult
from app.services.forensics_video import VideoForensicsResult
from app.services.risk_engine import compute_risk

_ZERO_AUDIO = AudioForensicsResult(synthetic_voice_score=0.0, signals={}, notes=[])
_ZERO_VIDEO = VideoForensicsResult(synthetic_video_score=0.0, signals={}, notes=[])
_MAX_AUDIO = AudioForensicsResult(synthetic_voice_score=1.0, signals={}, notes=[])
_MAX_VIDEO = VideoForensicsResult(synthetic_video_score=1.0, signals={}, notes=[])
_NEUTRAL_CLAIMS = {"overall_intent": "general_talk", "claimed_entities": [], "financial_claims": [], "red_flag_phrases": []}


def _compute(**overrides):
    kwargs = dict(
        audio_result=_ZERO_AUDIO,
        video_result=_ZERO_VIDEO,
        claims=_NEUTRAL_CLAIMS,
        registry_matches=[],
        lexicon_hits={},
    )
    kwargs.update(overrides)
    with patch("app.services.risk_engine.llm_client.try_generate_text", return_value="canned summary"):
        return compute_risk(**kwargs)


def test_lexicon_score_caps_at_one():
    """Covers TC G-02: summed lexicon category weights exceed 1.0 and must be capped before scoring."""
    lexicon_hits = {
        "impersonation_signal": ["a"],
        "insider_authority_claim": ["b"],
        "guaranteed_returns": ["c"],
        "unrealistic_multiplier": ["d"],
        "payment_solicitation": ["e"],
        "urgency_pressure": ["f"],
        "some_other_uncategorized_flag": ["g"],  # falls back to the 0.05 default weight
    }
    result = _compute(lexicon_hits=lexicon_hits)

    # weights['lexicon'] = 0.30; everything else is zeroed out by the neutral fixtures above,
    # so an uncapped sum (1.05) would leak through as 0.315 instead of exactly 0.30.
    assert result["risk_score"] == 0.3


def test_media_forensics_alone_drives_score_up():
    """Covers TC G-03: forensics-only signal shouldn't be flattened by empty claims/lexicon."""
    result = _compute(audio_result=_MAX_AUDIO, video_result=_MAX_VIDEO)
    # media_score = 0.6*1 + 0.4*1 = 1.0; weights['media_forensics'] = 0.35
    assert result["risk_score"] == 0.35
    assert result["risk_level"] == "MEDIUM"  # exercises the >=0.35 boundary exactly


def test_zero_signal_clip_is_low_risk():
    result = _compute()
    assert result["risk_score"] == 0.0
    assert result["risk_level"] == "LOW"


def test_fallback_summary_used_when_llm_unavailable():
    """Covers TC R-02: risk-synthesis fallback must cite the real score/level, not go silent."""
    with patch("app.services.risk_engine.llm_client.try_generate_text", return_value=None):
        result = compute_risk(_ZERO_AUDIO, _ZERO_VIDEO, _NEUTRAL_CLAIMS, [], {})

    assert "[Generated by rule-based fallback summarizer" in result["summary"]
    assert "LOW" in result["summary"]
