from unittest.mock import patch

from app.services.phishing_risk_engine import compute_phishing_risk


def _compute(**overrides):
    claims = {
        "claimed_sender": None,
        "urls_found": [],
        "requested_actions": [],
        "red_flag_phrases": [],
        "verdict": "likely_legitimate",
    }
    claims.update(overrides.pop("claims", {}))
    lexicon_hits = overrides.pop("lexicon_hits", {})
    with patch("app.services.phishing_risk_engine.llm_client.try_generate_text", return_value="canned summary"):
        return compute_phishing_risk(claims, lexicon_hits)


def test_benign_message_is_low_risk():
    result = _compute()
    assert result["risk_score"] == 0.0
    assert result["risk_level"] == "LOW"


def test_likely_phishing_verdict_drives_score_up():
    result = _compute(claims={"verdict": "likely_phishing"})
    # weights['verdict'] = 0.40 * _VERDICT_SCORE['likely_phishing'] (0.8) = 0.32
    assert result["risk_score"] == 0.32
    assert result["risk_level"] == "LOW"  # below the 0.35 MEDIUM cutoff on verdict alone


def test_phishing_verdict_plus_urls_plus_lexicon_reaches_high():
    result = _compute(
        claims={"verdict": "likely_phishing", "urls_found": ["https://evil.example.com"]},
        lexicon_hits={
            "credential_harvesting": ["verify your account"],
            "authority_impersonation": ["on behalf of sebi"],
            "financial_request": ["pay to unblock"],
        },
    )
    assert result["risk_level"] == "HIGH"


def test_fallback_summary_used_when_llm_unavailable():
    claims = {
        "claimed_sender": "SEBI",
        "urls_found": ["https://evil.example.com"],
        "requested_actions": [],
        "red_flag_phrases": [],
        "verdict": "likely_phishing",
    }
    with patch("app.services.phishing_risk_engine.llm_client.try_generate_text", return_value=None):
        result = compute_phishing_risk(claims, {})

    assert "[Generated by rule-based fallback summarizer" in result["summary"]
